# --- !Ups

CREATE TABLE ORGS      (
    "O_ID" BIGINT AUTO_INCREMENT NOT NULL
    , "NAME" VARCHAR NOT NULL
);
CREATE TABLE QUESTIONS (
    "Q_ID" BIGINT AUTO_INCREMENT NOT NULL
    , "TEXT" VARCHAR NOT NULL
    , "HINT1" VARCHAR NOT NULL
    , "HINT3" VARCHAR NOT NULL
    , "HINT5" VARCHAR NOT NULL
);
CREATE TABLE RESPONSES (
    "R_ID" BIGINT AUTO_INCREMENT NOT NULL
    ,"S_ID" BIGINT NOT NULL
    ,"Q_ID" BIGINT NOT NULL
    ,"U_ID" BIGINT NOT NULL
    ,"RESPONSE" INT NOT NULL
);
CREATE TABLE SURVEYS   (
    "S_ID" BIGINT AUTO_INCREMENT NOT NULL
    , "NAME" VARCHAR NOT NULL
);
CREATE TABLE SURVEY_QUESTIONS   (
    "S_ID" BIGINT NOT NULL
    , "Q_ID" BIGINT NOT NULL
);
CREATE TABLE USER_ORGS   (
    "U_ID" BIGINT NOT NULL
    , "O_ID" BIGINT NOT NULL
);
CREATE TABLE APP_USERS   (
    "U_ID" BIGINT NOT NULL
    , "UUID" UUID NOT NULL
);

# --- !Downs

DROP TABLE ORGS;
DROP TABLE QUESTIONS;
DROP TABLE QUESTIONS;
DROP TABLE RESPONSES;
DROP TABLE SURVEYS;
DROP TABLE SURVEY_QUESTIONS;
DROP TABLE USER_ORGS;
DROP TABLE APP_USERS;
